modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="chatsystem"
version="1.0.0"
displayName="Chat System"
description='''Shared chat system core for Forge.'''

[[dependencies.chatsystem]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
